// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestEFCoreRemoveThenAdd.Models;

namespace TestEFCoreRemoveThenAdd.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190425005600_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("TestEFCoreRemoveThenAdd.Models.Book", b =>
                {
                    b.Property<long>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Pages");

                    b.HasKey("BookId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("TestEFCoreRemoveThenAdd.Models.Book", b =>
                {
                    b.OwnsOne("TestEFCoreRemoveThenAdd.Models.Info", "EnglishInfo", b1 =>
                        {
                            b1.Property<long>("BookId");

                            b1.Property<string>("Title");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.HasOne("TestEFCoreRemoveThenAdd.Models.Book")
                                .WithOne("EnglishInfo")
                                .HasForeignKey("TestEFCoreRemoveThenAdd.Models.Info", "BookId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
