// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestEFCoreRemoveThenAdd.Models;

namespace TestEFCoreRemoveThenAdd.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("TestEFCoreRemoveThenAdd.Models.Book", b =>
                {
                    b.Property<long>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Pages");

                    b.HasKey("BookId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("TestEFCoreRemoveThenAdd.Models.Book", b =>
                {
                    b.OwnsOne("TestEFCoreRemoveThenAdd.Models.Info", "EnglishInfo", b1 =>
                        {
                            b1.Property<long?>("BookId");

                            b1.Property<string>("Title");

                            b1.ToTable("Books");

                            b1.HasOne("TestEFCoreRemoveThenAdd.Models.Book")
                                .WithOne("EnglishInfo")
                                .HasForeignKey("TestEFCoreRemoveThenAdd.Models.Info", "BookId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
